config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ExceptionLogger::Engine => '/exception_logger'
  # Devise
  devise_for :users, skip: %i[registrations], controllers: { sessions: 'sessions' }
  devise_scope :user do
    root to: 'dashboard#index'
  end

  # Dashboard
  get 'dashboard', to: 'dashboard#index'
  get 'get_volume_traded_by_month', to: 'dashboard#get_volume_traded_by_month'

  # MEMBERS
  get 'account/edit', to: 'members#edit'
  put 'account/edit_password', to: 'members#edit_password'
  get 'account/register', to: 'members#register'
  get '/convite/:username', to: 'members#register'
  patch 'member_change_password', to: 'members#member_change_password'
  post 'set_payment_password', to: 'members#set_payment_password'
  resources :members, except: [:index]

  # USERS
  resources :users, only: %i[index show edit update]

  # Cities
  get 'get_cities', to: 'cities#get_cities_by_state'
  get 'get_cities_by_name', to: 'cities#get_by_name'
  get 'concat_cities', to: 'cities#concat'
  get 'list', to: 'cities#list'

  # Accounts
  resources :accounts
  get 'get_account_from_ajax', to: 'accounts#get_account_from_ajax'
  get '/account/inactive', to: 'accounts#inactive'

  # AccountExtracts
  resources :account_extracts, only: [:index]

  # Incomes
  # resources :incomes, only: [:new, :create]

  # Outgoing
  resources :outgoings, only: %i[new create]

  resources :bank_transactions, only: %i[new create]

  # Recharges
  resources :recharges, only: %i[new create]
  post '/send_card_transaction', to: 'recharges#send_card_transaction'

  # SessionPayments (Middlewares)
  get '/outgoing_payment_password', to: 'session_payments#middleware_outgoing_payment_password'
  get '/bank_transaction_payment_password', to: 'session_payments#middleware_bank_transaction_payment_password'

  resources :products, except: [:show]

  resources :inventories, only: %i[index new create]

  namespace :api, defaults: { format: :json } do
    # CoinGueck paths
    get 'coins/list', to: 'coingecko#index'

    # Utils
    get 'persist_coins_list', to: 'utils#persist_coins_list'
    get 'persist_vs_currency', to: 'utils#persist_vs_currency'
  end
end

app/models/inventory.rb
# frozen_string_literal: true

class Inventory < ApplicationRecord
  belongs_to :product
  attr_accessor :amount_to_extract, :kind

  def self.generate_debit(params, logged_use)
    inventory = Inventory.find_by(product_id: params[:product_id])
    return  Inventory.new if inventory.nil?

    Inventory.transaction do
      inventory.amount_to_extract = params[:amount].to_i if params[:amount].to_i > 0
      inventory.amount += params[:amount].to_i

      generate_debit_extract(inventory, logged_use)
      inventory.save
      return inventory
    end
  end

  def self.generate_credit(params, logged_use)
    inventory = Inventory.find_by(product_id: params[:product_id])
    return Inventory.new if inventory.nil?

    Inventory.transaction do
      inventory.amount_to_extract = params[:amount].to_i if params[:amount].to_i > 0
      inventory.amount -= params[:amount].to_i

      generate_income_extract(inventory, logged_use)
      inventory.save
      return inventory
    end
  end

  def self.generate_debit_extract(inventory, logged_use)
    Outgoing.generate_debit(inventory, logged_use)
  end

  def self.generate_income_extract(inventory, logged_use)
    Income.generate_credit(inventory, logged_use)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @products = Inventory.all
  end

  def new
    @inventory = Inventory.new
  end

  def create
    respond_to do |format|
      @inventory = Inventory.generate_debit(inventory_params, current_user) if params[:kind].eql?('income')
      @inventory = Inventory.generate_credit(inventory_params, current_user) if params[:kind].eql?('outgoing')
      if @inventory
        format.html { redirect_to new_inventory_path, notice: 'O Estoque foi atualizado com sucesso.' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def inventory_params
    params
      .require(:inventory)
      .permit(
        :product_id,
        :amount
      )
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
  def kinds
    return { "Entrada" => 'income', "Saída" => 'outgoing'}
  end
end

app/views/inventories/_form.html.erb
<%= form_for(inventory) do |f| %>
  <% if inventory.errors.any? %>
    <div class="row">
      <ul class="collection with-header animated fadeInUp">
        <% if inventory.errors.count > 1 %>
          <li class="collection-header"><h5><%= inventory.errors.count %> erros impediram que o registro fosse salvo:</h5></li>
        <% else %>
          <li class="collection-header"><h5><%= inventory.errors.count %> erro impediu que o registro fosse salvo:</h5></li>
        <% end %>
        <% inventory.errors.full_messages.each do |message| %>
          <li class="collection-item valign-wrapper"><i class="material-icons">error_outline</i>&nbsp;<span> <%= message %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="row">
      <div class="col-12">
        <h4 class="form-section">Entrada de Produto</h4>
      </div>
    </div>

    <div class="row">
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Tipo", class: "" %>
          <%= select_tag(:kind, options_for_select(kinds, params[:kind]), { include_blank: false, class: " form-control" }) %>
        </fieldset>
      </div>

      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Produto", class: "" %>
          <%= f.collection_select(:product_id, Product.all, :id, :name, { include_blank: "" }, class: "select2 form-control", style:"width: 100%") %>
        </fieldset>
      </div>

      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Quantidade", class: "" %>
          <%= f.number_field :amount, required: true, class: "form-control" %>
        </fieldset>
      </div>
    </div>

    <div class="col-12">
      <div class="form-actions right">
        <div class="row d-flex justify-content-end">
          <div class="col-12 mb-1 justify-content-end">
            <button type="submit" class="btn btn-outline-primary js-submit form-submit" onclick="javascript: submitForm()" id="btn_submit">
              <i class="ft-check"></i> Salvar
            </button>
          </div>
        </div>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/inventories/_index.html.erb
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Estoque</h4>
          <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
          <div class="heading-elements">
            <div class="content-header-right d-flex justify-content-end">
              <button type="button" class="btn btn-secondary d-flex align-items-center mb-0 ml-1 px-2" data-toggle="modal" data-target="#default">
                <i class="fa fa-search"></i>&nbsp;&nbsp;Pesquisar
              </button>
            </div>
          </div>
        </div>

        <div class="card-content collapse show">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Categoria</th>
                    <th class="text-center">Qunatidade</th>
                    <th class="text-center">Valor de compra</th>
                    <th class="text-center">Valor de Venda</th>
                    <th class="text-center">Criado em.</th>
                    <th class="text-center">Atualizado em.</th>
                    <!--<th>Acões</th>-->
                  </tr>
                </thead>
                <tbody>
                  <% Inventory.all.each do |inventory| %>
                    <tr>
                      <td class="text-center"><%= inventory.product.name %></td>
                      <td class="text-center"><%= inventory.product.category&.name %></td>
                      <td class="text-center"><%= inventory.amount %></td>
                      <td class="text-center"><%= display_money(Money.new(inventory.product.purchase_price_cents * inventory.amount)) %></td>
                      <td class="text-center"><%= display_money(Money.new(inventory.product.sale_price_cents * inventory.amount)) %></td>
                      <td class="text-center"><%= br_date_format(inventory.created_at) %></td>
                      <td class="text-center"><%= br_date_format(inventory.updated_at) %></td>
                      <!--<td class="text-left cel-options">
                        <a href="#" class="dropdown-toggle btn btn-sm btn-outline-secondary btn-icon btn-option" data-toggle="dropdown" title="Opções" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-h"></i></a>
                        <div aria-labelledby="dropdownMenuLink" class="dropdown-menu">
                          <ul class="nav nav-hoverable flex-column">
                            <li class="nav-item">
                              <%#= link_to '<i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;Editar Produto'.html_safe, edit_product_path(product), data: { turbolinks: false }, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                              <%#= link_to '<i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;Adicionar ao Estoque'.html_safe, new_inventory_path, data: { turbolinks: false }, class: "nav-link" %>
                            </li>
                          </ul>
                        </div>
                      </td>-->
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <%#= will_paginate @products, previous_label: t("<"), next_label: t(">"), list_classes: %w(pagination justify-content-end mt-1) %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/inventories/new.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex align-items-center">
    <div class="content-header-left col-md-6 col-sm-6 col-6 mb-1">
      <h3 class="content-header-title mb-0">Gerenciar Estoque</h3>
    </div>
    <div class="content-header-right d-flex justify-content-end col-md-6 col-sm-6 col-6 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to products_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content collapse show">
          <div class="card-body">
            <%= render 'form', inventory: @inventory %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render 'index' %>
</div>