config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ExceptionLogger::Engine => '/exception_logger'
  # Devise
  devise_for :users, skip: %i[registrations], controllers: { sessions: 'sessions' }
  devise_scope :user do
    root to: 'dashboard#index'
  end

  # Dashboard
  get 'dashboard', to: 'dashboard#index'
  get 'get_volume_traded_by_month', to: 'dashboard#get_volume_traded_by_month'

  # MEMBERS
  get 'account/edit', to: 'members#edit'
  put 'account/edit_password', to: 'members#edit_password'
  get 'account/register', to: 'members#register'
  get '/convite/:username', to: 'members#register'
  patch 'member_change_password', to: 'members#member_change_password'
  post 'set_payment_password', to: 'members#set_payment_password'
  resources :members, except: [:index]

  # USERS
  resources :users, only: %i[index show edit update]

  # Cities
  get 'get_cities', to: 'cities#get_cities_by_state'
  get 'get_cities_by_name', to: 'cities#get_by_name'
  get 'concat_cities', to: 'cities#concat'
  get 'list', to: 'cities#list'

  # Accounts
  resources :accounts
  get 'get_account_from_ajax', to: 'accounts#get_account_from_ajax'
  get '/account/inactive', to: 'accounts#inactive'

  # AccountExtracts
  resources :account_extracts, only: [:index]

  # Incomes
  # resources :incomes, only: [:new, :create]

  # Outgoing
  resources :outgoings, only: %i[new create]

  resources :bank_transactions, only: %i[new create]

  # Recharges
  resources :recharges, only: %i[new create]
  post '/send_card_transaction', to: 'recharges#send_card_transaction'

  # SessionPayments (Middlewares)
  get '/outgoing_payment_password', to: 'session_payments#middleware_outgoing_payment_password'
  get '/bank_transaction_payment_password', to: 'session_payments#middleware_bank_transaction_payment_password'

  resources :products, except: [:show]

  resources :inventories, only: %i[index new create]

  namespace :api, defaults: { format: :json } do
    # CoinGueck paths
    get 'coins/list', to: 'coingecko#index'

    # Utils
    get 'persist_coins_list', to: 'utils#persist_coins_list'
    get 'persist_vs_currency', to: 'utils#persist_vs_currency'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :invoice, optional: true
  has_one :inventory

  before_save :set_spread
  after_create :create_inventory

  monetize :sale_price_cents
  monetize :purchase_price_cents

  private

  def set_spread
    self.spread_cents = sale_price_cents - purchase_price_cents
    self.spread_fee = ((spread_cents * 100) / purchase_price_cents).to_d
  end

  def create_inventory
    inventory = Inventory.new
    inventory.product = self
    inventory.amount = 0
    inventory.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params
      .require(:product)
      .permit(
        :category_id,
        :invoice_id,
        :name,
        :bar_code,
        :purchase_price,
        :sale_price
      )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div class="row">
      <ul class="collection with-header animated fadeInUp">
        <% if product.errors.count > 1 %>
          <li class="collection-header"><h5><%= product.errors.count %> erros impediram que o registro fosse salvo:</h5></li>
        <% else %>
          <li class="collection-header"><h5><%= product.errors.count %> erro impediu que o registro fosse salvo:</h5></li>
        <% end %>
        <% product.errors.full_messages.each do |message| %>
          <li class="collection-item valign-wrapper"><i class="material-icons">error_outline</i>&nbsp;<span> <%= message %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="row">
      <div class="col-12">
        <h4 class="form-section">Dados do Produto</h4>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Categoria", class: "" %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blank: "" }, class: "select2 form-control", style:"width: 100%") %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Nome", class: "" %>
          <%= f.text_field :name, required: true, class: "form-control" %>
        </fieldset>
      </div>

      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Código de Barras", class: "" %>
          <%= f.text_field :bar_code, required: true, class: "form-control" %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Preço de Compra", class: "" %>
          <%= f.text_field :purchase_price, required: true, class: "form-control currency" %>
        </fieldset>
      </div>

      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Preço de Venda", class: "" %>
          <%= f.text_field :sale_price, required: true, class: "form-control currency" %>
        </fieldset>
      </div>
    </div>

    <div class="col-12">
      <div class="form-actions right">
        <div class="row d-flex justify-content-end">
          <div class="col-12 mb-1 justify-content-end">
            <button type="submit" class="btn btn-outline-primary js-submit form-submit" onclick="javascript: submitForm()" id="btn_submit">
              <i class="ft-check"></i> Salvar
            </button>
          </div>
        </div>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/products/edit.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex align-items-center">
    <div class="content-header-left col-md-6 col-sm-6 col-6 mb-1">
      <h3 class="content-header-title mb-0">Editar Produto</h3>
    </div>
    <div class="content-header-right d-flex justify-content-end col-md-6 col-sm-6 col-6 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to products_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content collapse show">
          <div class="card-body">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex align-items-center justify-content-end">
    <div class="content-header-left col-md-6 col-sm-6 mb-1">
      <h3 class="content-header-title mb-0">Produtos Cadastrados</h3>
    </div>

    <div class="content-header-left col-lg-3 offset-lg-3 col-md-4 col-sm-6 mb-0">
      <div class="card">
        <div class="card-header px-1 pt-1 pb-0">
          <h6 class="content-header-title mb-0 d-flex justify-content-start">Total</h6>
        </div>
        <div class="card-content px-1 pt0 pb-1">
          <div class="card-text">
            <h2 class="d-flex justify-content-end text-bold-600">
              <%= Product.count %>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Produtos</h4>
          <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
          <div class="heading-elements">
            <div class="content-header-right d-flex justify-content-end">
              <button type="button" class="btn btn-secondary d-flex align-items-center mb-0 ml-1 px-2" data-toggle="modal" data-target="#default">
                <i class="fa fa-search"></i>&nbsp;&nbsp;Pesquisar
              </button>
            </div>
          </div>
        </div>

        <div class="card-content collapse show">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Categoria</th>
                    <th class="text-center">Código de Barras</th>
                    <th class="text-center">Preço de Compra</th>
                    <th class="text-center">Preço de Venda</th>
                    <th class="text-center">Spread</th>
                    <th class="text-center">Criado em.</th>
                    <th class="text-center">Atualizado em.</th>
                    <th>Acões</th>
                  </tr>
                </thead>
                <tbody>
                  <% @products.each do |product| %>
                    <tr>
                      <td class="text-center"><%= product.name %></td>
                      <td class="text-center"><%= product.category&.name %></td>
                      <td class="text-center"><%= product.bar_code %></td>
                      <td class="text-center"><%= display_money(Money.new(product.purchase_price_cents)) %></td>
                      <td class="text-center"><%= display_money(Money.new(product.sale_price_cents)) %></td>
                      <td class="text-center"><%= product.spread_fee %></td>
                      <td class="text-center"><%= br_date_format(product.created_at) %></td>
                      <td class="text-center"><%= br_date_format(product.updated_at) %></td>
                      <td class="text-left cel-options">
                        <a href="#" class="dropdown-toggle btn btn-sm btn-outline-secondary btn-icon btn-option" data-toggle="dropdown" title="Opções" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-h"></i></a>
                        <div aria-labelledby="dropdownMenuLink" class="dropdown-menu">
                          <ul class="nav nav-hoverable flex-column">
                            <li class="nav-item">
                              <%= link_to '<i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;Editar Produto'.html_safe, edit_product_path(product), data: { turbolinks: false }, class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                              <%= link_to '<i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;Adicionar ao Estoque'.html_safe, new_inventory_path, data: { turbolinks: false }, class: "nav-link" %>
                            </li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <%#= will_paginate @products, previous_label: t("<"), next_label: t(">"), list_classes: %w(pagination justify-content-end mt-1) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade text-left" id="default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel1"><i class="ft-filter"></i>&nbsp;&nbsp;Filtro</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form class="form">
        <div class="modal-body">
          <div class="form-body">

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="issueinput2">Tipo</label>
                  <%#= select_tag(:type_register, options_for_select(AccountExtract.type_registers.keys.map{|type_register|[AccountExtract.human_enum_name(:type_register, type_register), AccountExtract.type_registers[type_register]]}, params[:type_register]), { include_blank: "Todos", class: " form-control" }) %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="issueinput3">Data Inicial</label>
                  <%#= date_field_tag "date_filter_inicial", nil, class: "form-control datepicker", value: "#{(params[:date_filter_inicial])}", placeholder: "Data inicial" %>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label for="issueinput4">Data Final</label>
                  <%#= date_field_tag "date_filter_final", nil, class: "form-control datepicker", value: "#{(params[:date_filter_final])}", placeholder: "Data inicial" %>
                </div>
              </div>
            </div>

            <% unless params[:user_id].nil? %>
              <input type="hidden" name="user_id" value="<%= params[:user_id] %>">
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;&nbsp;Cancelar</button>
          <button type="submit" class="btn btn-outline-primary"><i class="fa fa-search"></i>&nbsp;&nbsp;Pesquisar</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex align-items-center">
    <div class="content-header-left col-md-6 col-sm-6 col-6 mb-1">
      <h3 class="content-header-title mb-0">Novo Produto</h3>
    </div>
    <div class="content-header-right d-flex justify-content-end col-md-6 col-sm-6 col-6 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to products_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content collapse show">
          <div class="card-body">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @product.Category %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @product.Invoice %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Bar code:</strong>
  <%= @product.bar_code %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= @product.purchase_price %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @product.sale_price %>
</p>

<p>
  <strong>Spread:</strong>
  <%= @product.spread %>
</p>

<p>
  <strong>Spread fee:</strong>
  <%= @product.spread_fee %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>