config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ExceptionLogger::Engine => '/exception_logger'
  # Devise
  devise_for :users, skip: %i[registrations], controllers: { sessions: 'sessions' }
  devise_scope :user do
    root to: 'dashboard#index'
  end

  # Dashboard
  get 'dashboard', to: 'dashboard#index'
  get 'get_volume_traded_by_month', to: 'dashboard#get_volume_traded_by_month'

  # MEMBERS
  get 'account/edit', to: 'members#edit'
  put 'account/edit_password', to: 'members#edit_password'
  get 'account/register', to: 'members#register'
  get '/convite/:username', to: 'members#register'
  patch 'member_change_password', to: 'members#member_change_password'
  post 'set_payment_password', to: 'members#set_payment_password'
  resources :members, except: [:index]

  # USERS
  resources :users, only: %i[index show edit update]

  # Cities
  get 'get_cities', to: 'cities#get_cities_by_state'
  get 'get_cities_by_name', to: 'cities#get_by_name'
  get 'concat_cities', to: 'cities#concat'
  get 'list', to: 'cities#list'

  # Accounts
  resources :accounts
  get 'get_account_from_ajax', to: 'accounts#get_account_from_ajax'
  get '/account/inactive', to: 'accounts#inactive'

  # AccountExtracts
  resources :account_extracts, only: [:index]

  # Incomes
  # resources :incomes, only: [:new, :create]

  # Outgoing
  resources :outgoings, only: %i[new create]

  resources :bank_transactions, only: %i[new create]

  # Recharges
  resources :recharges, only: %i[new create]
  post '/send_card_transaction', to: 'recharges#send_card_transaction'

  # SessionPayments (Middlewares)
  get '/outgoing_payment_password', to: 'session_payments#middleware_outgoing_payment_password'
  get '/bank_transaction_payment_password', to: 'session_payments#middleware_bank_transaction_payment_password'

  resources :products, except: [:show]

  resources :inventories, only: %i[index new create]

  namespace :api, defaults: { format: :json } do
    # CoinGueck paths
    get 'coins/list', to: 'coingecko#index'

    # Utils
    get 'persist_coins_list', to: 'utils#persist_coins_list'
    get 'persist_vs_currency', to: 'utils#persist_vs_currency'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include Filterable

  belongs_to :bank
  belongs_to :user

  enum account_type: %i[cc cp]

  scope :actives, -> { where(active: true) }
  scope :bank_id, ->(bank_id) { where(bank_id: bank_id) }
  scope :kind, ->(type) { where(account_type: type) }
  scope :agency, ->(agency) { where(agency_number: agency) }
  scope :account_number, -> (account_number) { where(account_number: account_number) }

  def inactive
    self.update(active: false)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_root_access!, only: %i[index]
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    if @account.nil?
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: 'Você ainda não tem uma conta cadastrada.' }
      end
    end
  end

  # GET /accounts/new
  def new
      if current_user.account.nil?
        @account = Account.new
      else
        respond_to do |format|
          format.html { redirect_to dashboard_path, notice: 'Você ja tem uma conta cadastrada.' }
        end
      end
  end

  # GET /accounts/1/edit
  def edit
    if @account.nil?
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: 'Você ainda não tem uma conta cadastrada.' }
      end
    end
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Conta criada com sucesso.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Conta atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_account_from_ajax
    @accounts = Account.filter(Account.actives, params.slice(:bank_id, :kind, :agency, :account_number))
    json_response(@accounts, :ok)
  end

  def inactive
    current_user.account.inactive
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Conta desativada com sucesso.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = nil
      @account = current_user.account unless current_user.account.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :bank_id, :agency_number, :account_number, :account_type)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(account, :html => {class: "page-body list", multipart: true}) do |f| %>
  <% if account.errors.any? %>
    <div class="row">
      <ul class="collection with-header animated fadeInUp">
        <% if account.errors.count > 1 %>
          <li class="collection-header"><h5><%= account.errors.count %> erros impediram que o registro fosse salvo:</h5></li>
        <% else %>
          <li class="collection-header"><h5><%= account.errors.count %> erro impediu que o registro fosse salvo:</h5></li>
        <% end %>
        <% account.errors.full_messages.each do |message| %>
          <li class="collection-item valign-wrapper"><i class="material-icons">error_outline</i>&nbsp;<span> <%= message %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="row">
      <div class="col-12">
        <h4 class="form-section">Dados da Conta</h4>
      </div>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Banco", class: "" %>
          <%= f.collection_select(:bank_id, Bank.all, :id, :name, { include_blank: "" }, class: "select2 form-control", style:"width: 100%", required: true) %>
        </fieldset>
      </div>
    
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label :agency_number, class: "" %>
          <%= f.text_field :agency_number, required: true, class: "form-control" %>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label :account_number, class: "" %>
          <%= f.text_field :account_number, required: true, class: "form-control" %>
        </fieldset>
      </div>

      <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-0">
        <fieldset class="form-group">
          <span class="danger">*</span>
          <%= f.label "Tipo", class: "" %>
          <%= f.select(:account_type, Account.account_types.keys.map {|account_type| [Account.human_enum_name(:account_type, account_type), account_type]}, { include_blank: false }, class: "form-control browser-default", id: 'account_type') %>
        </fieldset>
      </div>
    </div>

    <div class="col-12">
      <div class="form-actions right">
        <div class="row d-flex justify-content-end">
          <div class="col-12 mb-1 justify-content-end">
            <button type="submit" class="btn btn-outline-primary js-submit form-submit" onclick="javascript: submitForm()" id="btn_submit">
              <i class="ft-check"></i> Salvar
            </button>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
<% end %>

<script>
  disableFields(true);

  $('#account_bank_id').change(function () {
    if (this.value != ''){
      disableFields(false);
    } else {
      disableFields(true);
    }
  });

  function disableFields(boolean) {
    $('#account_agency_number').prop( "disabled", boolean );
    $('#account_account_number').prop( "disabled", boolean );
    $('#account_type').prop( "disabled", boolean );
  }
</script>

app/views/accounts/edit.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex align-items-center">
    <div class="content-header-left col-md-6 col-sm-6 col-6 mb-1">
      <h3 class="content-header-title mb-0">Editar Conta</h3>
    </div>
    <div class="content-header-right d-flex justify-content-end col-md-6 col-sm-6 col-6 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to dashboard_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content collapse show">
          <div class="card-body">
            <%= render 'form', account: @account %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col s8 m8">
    <h4 class="hydra-title--page">
      Accounts Cadastrados
    </h4>
  </div>
  <div class="col s4 m4">
    <%= form_tag accounts_path, :method => "get" do %>
      <input id="search_term" name="search_term" type="search" 
      placeholder="Pesquisar" class="hydra-input--search" value="<%= !@search.nil? ? @search : '' %>" required>
    <% end %>
  </div>
</div>

<div class="fixed-action-btn vertical">
  <a class="btn-floating btn-large orange">
    <i class="large material-icons">apps</i>
  </a>
  <ul>
    <li>
      <%= link_to new_account_path, class: "btn-floating red" do %>
        <i class="material-icons">add</i>
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col s12 m12">
    <div class="card-panel">
      <div class="card-content">
        <table class="striped">
          <thead>
            <tr>
                            <th>
                Bank
              </th>
                            <th>
                Agency number
              </th>
                            <th>
                Account number
              </th>
                            <th>
                Account type
              </th>
                            <th style="width: 110px">#</th>
            </tr>
          </thead>
          <tbody>
            <% @accounts.each do |
              account | %>
                <tr>
                                      <td>
                      <%= account.
                        bank%>
                    </td>
                                        <td>
                      <%= account.
                        agency_number%>
                    </td>
                                        <td>
                      <%= account.
                        account_number%>
                    </td>
                                        <td>
                      <%= account.
                        account_type%>
                    </td>
                                        <td>
                      <a class='dropdown-button btn' href='#' data-activates='ddoptions-<%= account.id %>' data-constrainWidth="false">Opções</a>
                      <ul id='ddoptions-<%= account.id %>' class='dropdown-content large'>
                        <li>
                          <%= link_to edit_account_path(account) do %>
                            <i class="material-icons">edit</i>Editar
                          <% end %>
                        </li>
                        <li>
                          <%= link_to account, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                            <i class="material-icons">delete</i>Remover
                          <% end %>
                        </li>
                      </ul>
                    </td>
                </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="content-wrapper">
  <div class="content-header row d-flex justify-content-end align-items-center">
    <div class="content-header-right d-flex justify-content-end col-md-6 col-sm-6 col-6 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to dashboard_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content collapse show">
          <div class="card-body">
            <%= render 'form', account: @account %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="content-wrapper">

  <div class="content-header row d-flex align-items-center">
    <div class="content-header-left col-xl-6 col-lg-6 col-md-6 col-sm-12 mb-1">
      <h3 class="content-header-title mb-0">Detalhes da Conta</h3>
    </div>
    <div class="content-header-right d-flex justify-content-end col-md-6 col-12 mb-1">
      <div class="btn-group float-md-right ml-1">
        <%= link_to edit_account_path(@account), class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-edit-2"></i>&nbsp;&nbsp;Editar
        <% end %>
      </div>

      <div class="btn-group float-md-right ml-1">
        <%= link_to dashboard_path, class:"btn btn-outline-primary d-flex align-items-center" do %>
          <i class="ft-arrow-left"></i>&nbsp;&nbsp;Voltar
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Dados da Conta</h4>
          <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
        </div>
        <div class="card-content collapse show">
          <div class="card-body">

            <form class="form">
              <div class="form-body">
                <h4 class="form-section">Informações da Conta</h4>
                <div class="row">

                  <div class="col-md-12">
                    <label class="text-bold-600">Banco:</label>
                    <span><%= @account.bank.name %></span>
                  </div>

                  <div class="col-md-12">
                    <label class="text-bold-600">Agência:</label>
                    <span><%=  @account.agency_number %></span>
                  </div>

                  <div class="col-md-12">
                    <label class="text-bold-600">Número da Conta:</label>
                    <span><%= @account.account_number %></span>
                  </div>

                  <div class="col-md-3">
                    <label class="text-bold-600">Tipo:</label>
                    <span><%=  Account.human_enum_name(:account_type, @account.account_type)  %></span>
                  </div>

                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>